### ISSUE TITLE
Help with assembly files

### ISSUE THREAD

**Issue by Perisys1312** [ScatteredDrifter/Buran-Ortho#4]
JLCPCB, using the "buran-BOM.csv" and "buran-pos-bottom.csv" files for BOM and CPL respectively, and the gerber-buran-pcb.zip for the gerber file, all from the repository and not release files, align themselves weirdly and I'm unsure if it's safe to order. I'd like some help on how to order and do this properly, if possible.

Edit: I manually readjusted them myself following the kicad project very closely.

**Comment by ScatteredDrifter** [comment]
Hey, Sorry for responding so late, I barely notice the messages here, excuse me! 
Jlcs preview is a little weird and usually they will be aligned again once they've put them into production, review to be specific. 
Readjusting them is also possible, yet I haven't put effort into it yet.

**Comment by Perisys1312** [comment]
> Hey, Sorry for responding so late, I barely notice the messages here, excuse me! Jlcs preview is a little weird and usually they will be aligned again once they've put them into production, review to be specific. Readjusting them is also possible, yet I haven't put effort into it yet.

That's alright! Thank you regardless, another question while I'm here, do you have any suggestions as to where I should print the plate? It's too thin for JLCPCB to accept it. 
And also, is the thickness of the plate flexible with the case design, because if so I might thicken them in a 3D editor, or just get them printed as FR4 instead.

**Comment by ScatteredDrifter** [comment]
Hm I can only recommend some shops that are usually available in Europe. Some would be 42keebs.eu or Snijab.nl, however I usually simply 3d printed them with a typical FDM printer. 
As for flexibility of thickness:
One could increase the thickness and adapt that to another, Which would thickness would you use? I could adapt the case for it then. 
Quick questions: Doesn't JLCPCB usually allow for 1.6mm thick pcbs, which would be the default thickness of this cases plate.

**Comment by Perisys1312** [comment]
I forgot to account for conversion, JLC requires 1cm thickness minimum for 3D printing, I'll use FR4 instead because it feels much better in my opinion. My apologies

(Also the DXF is very off and needed a lot of editing to work quite right as edgecuts, if you'd like, I can possibly supply GERBER files for an FR4 plate)
