### ISSUE TITLE
Compiling firmware causes duplicate keys

### ISSUE THREAD

**Issue by Ethanvdw** [ScatteredDrifter/Buran-Ortho#5]
I've noticed an issue when trying to compile the vial firmware to increase the layer count.

The two keys marked "3,7" in this image seem to have their functionality tied together.
![image](https://github.com/ScatteredDrifter/Buran-Ortho/assets/22869960/2d3c87ba-0bc4-4e59-b5f8-6c47fc78f7e8)

The issue isn't present in buran_kle.json, but somehow still impacts compiled firmware

**Comment by monsyuun** [comment]
Update: Changing cols to 12 in fixes it, but moves all the other keys to the wrong position.
